class AddAdditionalTables < ActiveRecord::Migration[5.0]
  def change
    create_table :aircrafts, force: :cascade do |t|
      t.string   "shop_num"
      t.string   "year"
      t.string   "make_model"
      t.string   "original_assign"
      t.string   "second_assign"
      t.string   "third_assign"
      t.string   "notes"
      t.boolean  "show_img"
      t.string   "show_img_cap"
      t.string   "img_link"
      t.string   "caption"
      t.string   "img_link_two"
      t.string   "caption_two"
      t.datetime "created_at",         null: false
      t.datetime "updated_at",         null: false
    end

    create_table :sequences, force: :cascade do |t|
      t.string   "company"
      t.string   "signature"
      t.string   "start_date"
      t.string   "motorized"
      t.string   "transfer_date"
      t.string   "quarters"
      t.string   "quarters_two"
      t.string   "quarters_three"
      t.string   "quarters_four"
      t.string   "quarters_five"
      t.string   "notes_one"
      t.string   "notes_two"
      t.string   "first"
      t.string   "first_photo"
      t.string   "second"
      t.string   "second_photo"
      t.string   "third"
      t.string   "third_photo"
      t.string   "fourth"
      t.string   "fourth_photo"
      t.string   "fifth"
      t.string   "fifth_photo"
      t.string   "sixth"
      t.string   "sixth_photo"
      t.string   "seventh"
      t.string   "seventh_photo"
      t.string   "eighth"
      t.string   "eighth_photo"
      t.string   "ninth"
      t.string   "ninth_photo"
      t.string   "tenth"
      t.string   "tenth_photo"
      t.string   "eleventh"
      t.string   "eleventh_photo"
      t.string   "twelfth"
      t.string   "twelfth_photo"
      t.string   "thirteenth"
      t.string   "thirteenth_photo"
      t.string   "fourteenth"
      t.string   "fourteenth_photo"
      t.string   "fifteenth"
      t.string   "fifteenth_photo"
      t.string   "sixteenth"
      t.string   "sixteenth_photo"
      t.string   "seventeenth"
      t.string   "seventeenth_photo"
      t.string   "eighteenth"
      t.string   "eighteenth_photo"
      t.string   "nineteenth"
      t.string   "nineteenth_photo"
      t.string   "twentieth"
      t.string   "twentieth_photo"
      t.string   "twenty_first"
      t.string   "twenty_first_photo"
      t.string   "twenty_second"
      t.string   "twenty_second_photo"
      t.string   "twenty_third"
      t.string   "twenty_third_photo"
      t.string   "twenty_fourth"
      t.string   "twenty_fourth_photo"
      t.string   "twenty_fifth"
      t.string   "twenty_fifth_photo"
      t.string   "twenty_sixth"
      t.string   "twenty_sixth_photo"
      t.string   "twenty_seventh"
      t.string   "twenty_seventh_photo"
      t.string   "twenty_eighth"
      t.string   "twenty_eighth_photo"
      t.string   "twenty_ninth"
      t.string   "twenty_ninth_photo"
      t.string   "thirtieth"
      t.string   "thirtieth_photo"
      t.datetime "created_at",           null: false
      t.datetime "updated_at",           null: false
    end
  end
end
