class AddMoreRelevantColumns < ActiveRecord::Migration[5.0]
  def change
    add_column :sequences, :reorganization_date, :string
    add_column :sequences, :fourth_rig_shop_num, :string
    add_column :sequences, :fourth_rig_dates, :daterange
    add_column :sequences, :fifth_rig_shop_num, :string
    add_column :sequences, :fifth_rig_dates, :daterange
    add_column :sequences, :sixth_rig_shop_num, :string
    add_column :sequences, :sixth_rig_dates, :daterange
    add_column :sequences, :seventh_rig_shop_num, :string
    add_column :sequences, :seventh_rig_dates, :daterange
    add_column :sequences, :eighth_rig_shop_num, :string
    add_column :sequences, :eighth_rig_dates, :daterange
    add_column :sequences, :ninth_rig_shop_num, :string
    add_column :sequences, :ninth_rig_dates, :daterange
    add_column :sequences, :tenth_rig_shop_num, :string
    add_column :sequences, :tenth_rig_dates, :daterange
    add_column :sequences, :eleventh_rig_shop_num, :string
    add_column :sequences, :eleventh_rig_dates, :daterange
    add_column :sequences, :twelfth_rig_shop_num, :string
    add_column :sequences, :twelfth_rig_dates, :daterange
    add_column :sequences, :thirteenth_rig_shop_num, :string
    add_column :sequences, :thirteenth_rig_dates, :daterange
    add_column :sequences, :fourteenth_rig_shop_num, :string
    add_column :sequences, :fourteenth_rig_dates, :daterange
    add_column :sequences, :fifteenth_rig_shop_num, :string
    add_column :sequences, :fifteenth_rig_dates, :daterange
    add_column :sequences, :sixteenth_rig_shop_num, :string
    add_column :sequences, :sixteenth_rig_dates, :daterange
    add_column :sequences, :seventeenth_rig_shop_num, :string
    add_column :sequences, :seventeenth_rig_dates, :daterange
    add_column :sequences, :eighteenth_rig_shop_num, :string
    add_column :sequences, :eighteenth_rig_dates, :daterange
    add_column :sequences, :nineteenth_rig_shop_num, :string
    add_column :sequences, :nineteenth_rig_dates, :daterange
    add_column :sequences, :twentieth_rig_shop_num, :string
    add_column :sequences, :twentieth_rig_dates, :daterange
    add_column :sequences, :twenty_first_rig_shop_num, :string
    add_column :sequences, :twenty_first_rig_dates, :daterange
    add_column :sequences, :twenty_second_rig_shop_num, :string
    add_column :sequences, :twenty_second_rig_dates, :daterange
    add_column :sequences, :twenty_third_rig_shop_num, :string
    add_column :sequences, :twenty_third_rig_dates, :daterange
    add_column :sequences, :twenty_fourth_rig_shop_num, :string
    add_column :sequences, :twenty_fourth_rig_dates, :daterange
    add_column :sequences, :twenty_fifth_rig_shop_num, :string
    add_column :sequences, :twenty_fifth_rig_dates, :daterange
    add_column :sequences, :twenty_sixth_rig_shop_num, :string
    add_column :sequences, :twenty_sixth_rig_dates, :daterange
    add_column :sequences, :twenty_seventh_rig_shop_num, :string
    add_column :sequences, :twenty_seventh_rig_dates, :daterange
    add_column :sequences, :twenty_eighth_rig_shop_num, :string
    add_column :sequences, :twenty_eighth_rig_dates, :daterange
    add_column :sequences, :twenty_ninth_rig_shop_num, :string
    add_column :sequences, :twenty_ninth_rig_dates, :daterange
    add_column :sequences, :thirtieth_rig_shop_num, :string
    add_column :sequences, :thirtieth_rig_dates, :daterange
  end
end
