class AddColumnsToSequences91921 < ActiveRecord::Migration[5.0]
  def change
    add_column :sequences, :hundred_and_thirty_first_shop_num, :string
    add_column :sequences, :hundred_and_thirty_first, :string
    add_column :sequences, :hundred_and_thirty_first_rig_dates, :daterange
    add_column :sequences, :hundred_and_thirty_second_shop_num, :string
    add_column :sequences, :hundred_and_thirty_second, :string
    add_column :sequences, :hundred_and_thirty_second_rig_dates, :daterange
    add_column :sequences, :hundred_and_thirty_third_shop_num, :string
    add_column :sequences, :hundred_and_thirty_third, :string
    add_column :sequences, :hundred_and_thirty_third_rig_dates, :daterange
    add_column :sequences, :hundred_and_thirty_fourth_shop_num, :string
    add_column :sequences, :hundred_and_thirty_fourth, :string
    add_column :sequences, :hundred_and_thirty_fourth_rig_dates, :daterange
    add_column :sequences, :hundred_and_thirty_fifth_shop_num, :string
    add_column :sequences, :hundred_and_thirty_fifth, :string
    add_column :sequences, :hundred_and_thirty_fifth_rig_dates, :daterange
    add_column :sequences, :hundred_and_thirty_sixth_shop_num, :string
    add_column :sequences, :hundred_and_thirty_sixth, :string
    add_column :sequences, :hundred_and_thirty_sixth_rig_dates, :daterange
    add_column :sequences, :hundred_and_thirty_seventh_shop_num, :string
    add_column :sequences, :hundred_and_thirty_seventh, :string
    add_column :sequences, :hundred_and_thirty_seventh_rig_dates, :daterange
    add_column :sequences, :hundred_and_thirty_eighth_shop_num, :string
    add_column :sequences, :hundred_and_thirty_eighth, :string
    add_column :sequences, :hundred_and_thirty_eighth_rig_dates, :daterange
    add_column :sequences, :hundred_and_thirty_ninth_shop_num, :string
    add_column :sequences, :hundred_and_thirty_ninth, :string
    add_column :sequences, :hundred_and_thirty_ninth_rig_dates, :daterange
    add_column :sequences, :hundred_and_fortieth_shop_num, :string
    add_column :sequences, :hundred_and_fortieth, :string
    add_column :sequences, :hundred_and_fortieth_rig_dates, :daterange
    add_column :sequences, :hundred_and_forty_first_shop_num, :string
    add_column :sequences, :hundred_and_forty_first, :string
    add_column :sequences, :hundred_and_forty_first_rig_dates, :daterange
    add_column :sequences, :hundred_and_forty_second_shop_num, :string
    add_column :sequences, :hundred_and_forty_second, :string
    add_column :sequences, :hundred_and_forty_second_rig_dates, :daterange
    add_column :sequences, :hundred_and_forty_third_shop_num, :string
    add_column :sequences, :hundred_and_forty_third, :string
    add_column :sequences, :hundred_and_forty_third_rig_dates, :daterange
    add_column :sequences, :hundred_and_forty_fourth_shop_num, :string
    add_column :sequences, :hundred_and_forty_fourth, :string
    add_column :sequences, :hundred_and_forty_fourth_rig_dates, :daterange
    add_column :sequences, :hundred_and_forty_fifth_shop_num, :string
    add_column :sequences, :hundred_and_forty_fifth, :string
    add_column :sequences, :hundred_and_forty_fifth_rig_dates, :daterange
    add_column :sequences, :hundred_and_forty_sixth_shop_num, :string
    add_column :sequences, :hundred_and_forty_sixth, :string
    add_column :sequences, :hundred_and_forty_sixth_rig_dates, :daterange
    add_column :sequences, :hundred_and_forty_seventh_shop_num, :string
    add_column :sequences, :hundred_and_forty_seventh, :string
    add_column :sequences, :hundred_and_forty_seventh_rig_dates, :daterange
    add_column :sequences, :hundred_and_forty_eighth_shop_num, :string
    add_column :sequences, :hundred_and_forty_eighth, :string
    add_column :sequences, :hundred_and_forty_eighth_rig_dates, :daterange
    add_column :sequences, :hundred_and_forty_ninth_shop_num, :string
    add_column :sequences, :hundred_and_forty_ninth, :string
    add_column :sequences, :hundred_and_forty_ninth_rig_dates, :daterange
    add_column :sequences, :hundred_and_fiftieth_shop_num, :string
    add_column :sequences, :hundred_and_fiftieth, :string
    add_column :sequences, :hundred_and_fiftieth_rig_dates, :daterange
    add_column :sequences, :hundred_and_fifty_first_shop_num, :string
    add_column :sequences, :hundred_and_fifty_first, :string
    add_column :sequences, :hundred_and_fifty_first_rig_dates, :daterange
    add_column :sequences, :hundred_and_fifty_second_shop_num, :string
    add_column :sequences, :hundred_and_fifty_second, :string
    add_column :sequences, :hundred_and_fifty_second_rig_dates, :daterange
    add_column :sequences, :hundred_and_fifty_third_shop_num, :string
    add_column :sequences, :hundred_and_fifty_third, :string
    add_column :sequences, :hundred_and_fifty_third_rig_dates, :daterange
    add_column :sequences, :hundred_and_fifty_fourth_shop_num, :string
    add_column :sequences, :hundred_and_fifty_fourth, :string
    add_column :sequences, :hundred_and_fifty_fourth_rig_dates, :daterange
    add_column :sequences, :hundred_and_fifty_fifth_shop_num, :string
    add_column :sequences, :hundred_and_fifty_fifth, :string
    add_column :sequences, :hundred_and_fifty_fifth_rig_dates, :daterange
  end
end
