class AddAssignmentsToSequences < ActiveRecord::Migration[5.0]
  def change
    add_column :sequences, :fifty_first_rig_shop_num, :string
    add_column :sequences, :fifty_first, :string
    add_column :sequences, :fifty_first_rig_dates, :daterange
    add_column :sequences, :fifty_second_rig_shop_num, :string
    add_column :sequences, :fifty_second, :string
    add_column :sequences, :fifty_second_rig_dates, :daterange
    add_column :sequences, :fifty_third_rig_shop_num, :string
    add_column :sequences, :fifty_third, :string
    add_column :sequences, :fifty_third_rig_dates, :daterange
    add_column :sequences, :fifty_fourth_rig_shop_num, :string
    add_column :sequences, :fifty_fourth, :string
    add_column :sequences, :fifty_fourth_rig_dates, :daterange
    add_column :sequences, :fifty_fifth_rig_shop_num, :string
    add_column :sequences, :fifty_fifth, :string
    add_column :sequences, :fifty_fifth_rig_dates, :daterange
    add_column :sequences, :fifty_sixth_rig_shop_num, :string
    add_column :sequences, :fifty_sixth, :string
    add_column :sequences, :fifty_sixth_rig_dates, :daterange
    add_column :sequences, :fifty_seventh_rig_shop_num, :string
    add_column :sequences, :fifty_seventh, :string
    add_column :sequences, :fifty_seventh_rig_dates, :daterange
    add_column :sequences, :fifty_eighth_rig_shop_num, :string
    add_column :sequences, :fifty_eighth, :string
    add_column :sequences, :fifty_eighth_rig_dates, :daterange
    add_column :sequences, :fifty_ninth_rig_shop_num, :string
    add_column :sequences, :fifty_ninth, :string
    add_column :sequences, :fifty_ninth_rig_dates, :daterange
    add_column :sequences, :sixtieth_rig_shop_num, :string
    add_column :sequences, :sixtieth, :string
    add_column :sequences, :sixtieth_rig_dates, :daterange
    add_column :sequences, :sixty_first_rig_shop_num, :string
    add_column :sequences, :sixty_first, :string
    add_column :sequences, :sixty_first_rig_dates, :daterange
    add_column :sequences, :sixty_second_rig_shop_num, :string
    add_column :sequences, :sixty_second, :string
    add_column :sequences, :sixty_second_rig_dates, :daterange
    add_column :sequences, :sixty_third_rig_shop_num, :string
    add_column :sequences, :sixty_third, :string
    add_column :sequences, :sixty_third_rig_dates, :daterange
    add_column :sequences, :sixty_fourth_rig_shop_num, :string
    add_column :sequences, :sixty_fourth, :string
    add_column :sequences, :sixty_fourth_rig_dates, :daterange
    add_column :sequences, :sixty_fifth_rig_shop_num, :string
    add_column :sequences, :sixty_fifth, :string
    add_column :sequences, :sixty_fifth_rig_dates, :daterange
    add_column :sequences, :sixty_sixth_rig_shop_num, :string
    add_column :sequences, :sixty_sixth, :string
    add_column :sequences, :sixty_sixth_rig_dates, :daterange
    add_column :sequences, :sixty_seventh_rig_shop_num, :string
    add_column :sequences, :sixty_seventh, :string
    add_column :sequences, :sixty_seventh_rig_dates, :daterange
    add_column :sequences, :sixty_eighth_rig_shop_num, :string
    add_column :sequences, :sixty_eighth, :string
    add_column :sequences, :sixty_eighth_rig_dates, :daterange
    add_column :sequences, :sixty_ninth_rig_shop_num, :string
    add_column :sequences, :sixty_ninth, :string
    add_column :sequences, :sixty_ninth_rig_dates, :daterange
    add_column :sequences, :seventieth_rig_shop_num, :string
    add_column :sequences, :seventieth, :string
    add_column :sequences, :seventieth_rig_dates, :daterange
    add_column :sequences, :seventy_first_rig_shop_num, :string
    add_column :sequences, :seventy_first, :string
    add_column :sequences, :seventy_first_rig_dates, :daterange
    add_column :sequences, :seventy_second_rig_shop_num, :string
    add_column :sequences, :seventy_second, :string
    add_column :sequences, :seventy_second_rig_dates, :daterange
    add_column :sequences, :seventy_third_rig_shop_num, :string
    add_column :sequences, :seventy_third, :string
    add_column :sequences, :seventy_third_rig_dates, :daterange
    add_column :sequences, :seventy_fourth_rig_shop_num, :string
    add_column :sequences, :seventy_fourth, :string
    add_column :sequences, :seventy_fourth_rig_dates, :daterange
    add_column :sequences, :seventy_fifth_rig_shop_num, :string
    add_column :sequences, :seventy_fifth, :string
    add_column :sequences, :seventy_fifth_rig_dates, :daterange
    add_column :sequences, :seventy_sixth_rig_shop_num, :string
    add_column :sequences, :seventy_sixth, :string
    add_column :sequences, :seventy_sixth_rig_dates, :daterange
    add_column :sequences, :seventy_seventh_rig_shop_num, :string
    add_column :sequences, :seventy_seventh, :string
    add_column :sequences, :seventy_seventh_rig_dates, :daterange
    add_column :sequences, :seventy_eighth_rig_shop_num, :string
    add_column :sequences, :seventy_eighth, :string
    add_column :sequences, :seventy_eighth_rig_dates, :daterange
    add_column :sequences, :seventy_ninth_rig_shop_num, :string
    add_column :sequences, :seventy_ninth, :string
    add_column :sequences, :seventy_ninth_rig_dates, :daterange
    add_column :sequences, :eightieth_rig_shop_num, :string
    add_column :sequences, :eightieth, :string
    add_column :sequences, :eightieth_rig_dates, :daterange
    add_column :sequences, :eighty_first_rig_shop_num, :string
    add_column :sequences, :eighty_first, :string
    add_column :sequences, :eighty_first_rig_dates, :daterange
    add_column :sequences, :eighty_second_rig_shop_num, :string
    add_column :sequences, :eighty_second, :string
    add_column :sequences, :eighty_second_rig_dates, :daterange
    add_column :sequences, :eighty_third_rig_shop_num, :string
    add_column :sequences, :eighty_third, :string
    add_column :sequences, :eighty_third_rig_dates, :daterange
    add_column :sequences, :eighty_fourth_rig_shop_num, :string
    add_column :sequences, :eighty_fourth, :string
    add_column :sequences, :eighty_fourth_rig_dates, :daterange
    add_column :sequences, :eighty_fifth_rig_shop_num, :string
    add_column :sequences, :eighty_fifth, :string
    add_column :sequences, :eighty_fifth_rig_dates, :daterange
    add_column :sequences, :eighty_sixth_rig_shop_num, :string
    add_column :sequences, :eighty_sixth, :string
    add_column :sequences, :eighty_sixth_rig_dates, :daterange
    add_column :sequences, :eighty_seventh_rig_shop_num, :string
    add_column :sequences, :eighty_seventh, :string
    add_column :sequences, :eighty_seventh_rig_dates, :daterange
    add_column :sequences, :eighty_eighth_rig_shop_num, :string
    add_column :sequences, :eighty_eighth, :string
    add_column :sequences, :eighty_eighth_rig_dates, :daterange
    add_column :sequences, :eighty_ninth_rig_shop_num, :string
    add_column :sequences, :eighty_ninth, :string
    add_column :sequences, :eighty_ninth_rig_dates, :daterange
    add_column :sequences, :nintieth_rig_shop_num, :string
    add_column :sequences, :nintieth, :string
    add_column :sequences, :nintieth_rig_dates, :daterange
    add_column :sequences, :ninety_first_rig_shop_num, :string
    add_column :sequences, :ninety_first, :string
    add_column :sequences, :ninety_first_rig_dates, :daterange
    add_column :sequences, :ninety_second_rig_shop_num, :string
    add_column :sequences, :ninety_second, :string
    add_column :sequences, :ninety_second_rig_dates, :daterange
    add_column :sequences, :ninety_third_rig_shop_num, :string
    add_column :sequences, :ninety_third, :string
    add_column :sequences, :ninety_third_rig_dates, :daterange
    add_column :sequences, :ninety_fourth_rig_shop_num, :string
    add_column :sequences, :ninety_fourth, :string
    add_column :sequences, :ninety_fourth_rig_dates, :daterange
    add_column :sequences, :ninety_fifth_rig_shop_num, :string
    add_column :sequences, :ninety_fifth, :string
    add_column :sequences, :ninety_fifth_rig_dates, :daterange
    add_column :sequences, :ninety_sixth_rig_shop_num, :string
    add_column :sequences, :ninety_sixth, :string
    add_column :sequences, :ninety_sixth_rig_dates, :daterange
    add_column :sequences, :ninety_seventh_rig_shop_num, :string
    add_column :sequences, :ninety_seventh, :string
    add_column :sequences, :ninety_seventh_rig_dates, :daterange
    add_column :sequences, :ninety_eighth_rig_shop_num, :string
    add_column :sequences, :ninety_eighth, :string
    add_column :sequences, :ninety_eighth_rig_dates, :daterange
    add_column :sequences, :ninety_ninth_rig_shop_num, :string
    add_column :sequences, :ninety_ninth, :string
    add_column :sequences, :ninety_ninth_rig_dates, :daterange
    add_column :sequences, :hundredth_rig_shop_num, :string
    add_column :sequences, :hundredth, :string
    add_column :sequences, :hundredth_rig_dates, :daterange
    add_column :sequences, :hundred_and_first_rig_shop_num, :string
    add_column :sequences, :hundred_and_first, :string
    add_column :sequences, :hundred_and_first_rig_dates, :daterange
    add_column :sequences, :hundred_and_second_rig_shop_num, :string
    add_column :sequences, :hundred_and_second, :string
    add_column :sequences, :hundred_and_second_rig_dates, :daterange
    add_column :sequences, :hundred_and_third_rig_shop_num, :string
    add_column :sequences, :hundred_and_third, :string
    add_column :sequences, :hundred_and_third_rig_dates, :daterange
    add_column :sequences, :hundred_and_fourth_rig_shop_num, :string
    add_column :sequences, :hundred_and_fourth, :string
    add_column :sequences, :hundred_and_fourth_rig_dates, :daterange
    add_column :sequences, :hundred_and_fifth_rig_shop_num, :string
    add_column :sequences, :hundred_and_fifth, :string
    add_column :sequences, :hundred_and_fifth_rig_dates, :daterange
    add_column :sequences, :hundred_and_sixth_rig_shop_num, :string
    add_column :sequences, :hundred_and_sixth, :string
    add_column :sequences, :hundred_and_sixth_rig_dates, :daterange
    add_column :sequences, :hundred_and_seventh_rig_shop_num, :string
    add_column :sequences, :hundred_and_seventh, :string
    add_column :sequences, :hundred_and_seventh_rig_dates, :daterange
    add_column :sequences, :hundred_and_eighth_rig_shop_num, :string
    add_column :sequences, :hundred_and_eighth, :string
    add_column :sequences, :hundred_and_eighth_rig_dates, :daterange
    add_column :sequences, :hundred_and_ninth_rig_shop_num, :string
    add_column :sequences, :hundred_and_ninth, :string
    add_column :sequences, :hundred_and_ninth_rig_dates, :daterange
    add_column :sequences, :hundred_and_tenth_rig_shop_num, :string
    add_column :sequences, :hundred_and_tenth, :string
    add_column :sequences, :hundred_and_tenth_rig_dates, :daterange
    add_column :sequences, :hundred_and_eleventh_rig_shop_num, :string
    add_column :sequences, :hundred_and_eleventh, :string
    add_column :sequences, :hundred_and_eleventh_rig_dates, :daterange
    add_column :sequences, :hundred_and_twelfth_rig_shop_num, :string
    add_column :sequences, :hundred_and_twelfth, :string
    add_column :sequences, :hundred_and_twelfth_rig_dates, :daterange
    add_column :sequences, :hundred_and_thirteenth_rig_shop_num, :string
    add_column :sequences, :hundred_and_thirteenth, :string
    add_column :sequences, :hundred_and_thirteenth_rig_dates, :daterange
    add_column :sequences, :hundred_and_fourteenth_rig_shop_num, :string
    add_column :sequences, :hundred_and_fourteenth, :string
    add_column :sequences, :hundred_and_fourteenth_rig_dates, :daterange
    add_column :sequences, :hundred_and_fifteenth_rig_shop_num, :string
    add_column :sequences, :hundred_and_fifteenth, :string
    add_column :sequences, :hundred_and_fifteenth_rig_dates, :daterange
    add_column :sequences, :hundred_and_sixteenth_rig_shop_num, :string
    add_column :sequences, :hundred_and_sixteenth, :string
    add_column :sequences, :hundred_and_sixteenth_rig_dates, :daterange
    add_column :sequences, :hundred_and_seventeenth_rig_shop_num, :string
    add_column :sequences, :hundred_and_seventeenth, :string
    add_column :sequences, :hundred_and_seventeenth_rig_dates, :daterange
    add_column :sequences, :hundred_and_eighteenth_rig_shop_num, :string
    add_column :sequences, :hundred_and_eighteenth, :string
    add_column :sequences, :hundred_and_eighteenth_rig_dates, :daterange
    add_column :sequences, :hundred_and_nineteenth_rig_shop_num, :string
    add_column :sequences, :hundred_and_nineteenth, :string
    add_column :sequences, :hundred_and_nineteenth_rig_dates, :daterange
    add_column :sequences, :hundred_and_twentieth_rig_shop_num, :string
    add_column :sequences, :hundred_and_twentieth, :string
    add_column :sequences, :hundred_and_twentieth_rig_dates, :daterange
    add_column :sequences, :hundred_and_twenty_first_rig_shop_num, :string
    add_column :sequences, :hundred_and_twenty_first, :string
    add_column :sequences, :hundred_and_twenty_first_rig_dates, :daterange
    add_column :sequences, :hundred_and_twenty_second_rig_shop_num, :string
    add_column :sequences, :hundred_and_twenty_second, :string
    add_column :sequences, :hundred_and_twenty_second_rig_dates, :daterange
    add_column :sequences, :hundred_and_twenty_third_rig_shop_num, :string
    add_column :sequences, :hundred_and_twenty_third, :string
    add_column :sequences, :hundred_and_twenty_third_rig_dates, :daterange
    add_column :sequences, :hundred_and_twenty_fourth_rig_shop_num, :string
    add_column :sequences, :hundred_and_twenty_fourth, :string
    add_column :sequences, :hundred_and_twenty_fourth_rig_dates, :daterange
    add_column :sequences, :hundred_and_twenty_fifth_rig_shop_num, :string
    add_column :sequences, :hundred_and_twenty_fifth, :string
    add_column :sequences, :hundred_and_twenty_fifth_rig_dates, :daterange
    add_column :sequences, :hundred_and_twenty_sixth_rig_shop_num, :string
    add_column :sequences, :hundred_and_twenty_sixth, :string
    add_column :sequences, :hundred_and_twenty_sixth_rig_dates, :daterange
    add_column :sequences, :hundred_and_twenty_seventh_rig_shop_num, :string
    add_column :sequences, :hundred_and_twenty_seventh, :string
    add_column :sequences, :hundred_and_twenty_seventh_rig_dates, :daterange
    add_column :sequences, :hundred_and_twenty_eighth_rig_shop_num, :string
    add_column :sequences, :hundred_and_twenty_eighth, :string
    add_column :sequences, :hundred_and_twenty_eighth_rig_dates, :daterange
    add_column :sequences, :hundred_and_twenty_ninth_rig_shop_num, :string
    add_column :sequences, :hundred_and_twenty_ninth, :string
    add_column :sequences, :hundred_and_twenty_ninth_rig_dates, :daterange
    add_column :sequences, :hundred_and_thirtieth_rig_shop_num, :string
    add_column :sequences, :hundred_and_thirtieth, :string
    add_column :sequences, :hundred_and_thirtieth_rig_dates, :daterange
  end
end
