class SequencesController < ApplicationController
  def index
    @sequences = Sequence.all.order(id: :asc)
    render 'index.html.erb'
  end

  def search_co_landing
    @search_heading = params[:search].to_date.strftime("%A, %B %e, %Y")
    search_term = params[:search].to_date.strftime("%Y-%m-%d")

    sequence1 = Sequence.select('id, company, signature, first_rig_shop_num AS "shop_num", first AS "rig"').where('first_rig_dates @> date ?', "#{search_term}")
    sequence2 = Sequence.select('id, company, signature, second_rig_shop_num AS "shop_num", second AS "rig"').where('second_rig_dates @> date ?', "#{search_term}")
    sequence3 = Sequence.select('id, company, signature, third_rig_shop_num AS "shop_num", third AS "rig"').where('third_rig_dates @> date ?', "#{search_term}")
    sequence4 = Sequence.select('id, company, signature, fourth_rig_shop_num AS "shop_num", fourth AS "rig"').where('fourth_rig_dates @> date ?', "#{search_term}")
    sequence5 = Sequence.select('id, company, signature, fifth_rig_shop_num AS "shop_num", fifth AS "rig"').where('fifth_rig_dates @> date ?', "#{search_term}")
    sequence6 = Sequence.select('id, company, signature, sixth_rig_shop_num AS "shop_num", sixth AS "rig"').where('sixth_rig_dates @> date ?', "#{search_term}")
    sequence7 = Sequence.select('id, company, signature, seventh_rig_shop_num AS "shop_num", seventh AS "rig"').where('seventh_rig_dates @> date ?', "#{search_term}")
    sequence8 = Sequence.select('id, company, signature, eighth_rig_shop_num AS "shop_num", eighth AS "rig"').where('eighth_rig_dates @> date ?', "#{search_term}")
    sequence9 = Sequence.select('id, company, signature, ninth_rig_shop_num AS "shop_num", ninth AS "rig"').where('ninth_rig_dates @> date ?', "#{search_term}")
    sequence10 = Sequence.select('id, company, signature, tenth_rig_shop_num AS "shop_num", tenth AS "rig"').where('tenth_rig_dates @> date ?', "#{search_term}")
    sequence11 = Sequence.select('id, company, signature, eleventh_rig_shop_num AS "shop_num", eleventh AS "rig"').where('eleventh_rig_dates @> date ?', "#{search_term}")
    sequence12 = Sequence.select('id, company, signature, twelfth_rig_shop_num AS "shop_num", twelfth AS "rig"').where('twelfth_rig_dates @> date ?', "#{search_term}")
    sequence13 = Sequence.select('id, company, signature, thirteenth_rig_shop_num AS "shop_num", thirteenth AS "rig"').where('thirteenth_rig_dates @> date ?', "#{search_term}")
    sequence14 = Sequence.select('id, company, signature, fourteenth_rig_shop_num AS "shop_num", fourteenth AS "rig"').where('fourteenth_rig_dates @> date ?', "#{search_term}")
    sequence15 = Sequence.select('id, company, signature, fifteenth_rig_shop_num AS "shop_num", fifteenth AS "rig"').where('fifteenth_rig_dates @> date ?', "#{search_term}")
    sequence16 = Sequence.select('id, company, signature, sixteenth_rig_shop_num AS "shop_num", sixteenth AS "rig"').where('sixteenth_rig_dates @> date ?', "#{search_term}")
    sequence17 = Sequence.select('id, company, signature, seventeenth_rig_shop_num AS "shop_num", seventeenth AS "rig"').where('seventeenth_rig_dates @> date ?', "#{search_term}")
    sequence18 = Sequence.select('id, company, signature, eighteenth_rig_shop_num AS "shop_num", eighteenth AS "rig"').where('eighteenth_rig_dates @> date ?', "#{search_term}")
    sequence19 = Sequence.select('id, company, signature, nineteenth_rig_shop_num AS "shop_num", nineteenth AS "rig"').where('nineteenth_rig_dates @> date ?', "#{search_term}")
    sequence20 = Sequence.select('id, company, signature, twentieth_rig_shop_num AS "shop_num", twentieth AS "rig"').where('twentieth_rig_dates @> date ?', "#{search_term}")
    sequence21 = Sequence.select('id, company, signature, twenty_first_rig_shop_num AS "shop_num", twenty_first AS "rig"').where('twenty_first_rig_dates @> date ?', "#{search_term}")
    sequence22 = Sequence.select('id, company, signature, twenty_second_rig_shop_num AS "shop_num", twenty_second AS "rig"').where('twenty_second_rig_dates @> date ?', "#{search_term}")
    sequence23 = Sequence.select('id, company, signature, twenty_third_rig_shop_num AS "shop_num", twenty_third AS "rig"').where('twenty_third_rig_dates @> date ?', "#{search_term}")
    sequence24 = Sequence.select('id, company, signature, twenty_fourth_rig_shop_num AS "shop_num", twenty_fourth AS "rig"').where('twenty_fourth_rig_dates @> date ?', "#{search_term}")
    sequence25 = Sequence.select('id, company, signature, twenty_fifth_rig_shop_num AS "shop_num", twenty_fifth AS "rig"').where('twenty_fifth_rig_dates @> date ?', "#{search_term}")
    sequence26 = Sequence.select('id, company, signature, twenty_sixth_rig_shop_num AS "shop_num", twenty_sixth AS "rig"').where('twenty_sixth_rig_dates @> date ?', "#{search_term}")
    sequence27 = Sequence.select('id, company, signature, twenty_seventh_rig_shop_num AS "shop_num", twenty_seventh AS "rig"').where('twenty_seventh_rig_dates @> date ?', "#{search_term}")
    sequence28 = Sequence.select('id, company, signature, twenty_eighth_rig_shop_num AS "shop_num", twenty_eighth AS "rig"').where('twenty_eighth_rig_dates @> date ?', "#{search_term}")
    sequence29 = Sequence.select('id, company, signature, twenty_ninth_rig_shop_num AS "shop_num", twenty_ninth AS "rig"').where('twenty_ninth_rig_dates @> date ?', "#{search_term}")
    sequence30 = Sequence.select('id, company, signature, thirtieth_rig_shop_num AS "shop_num", thirtieth AS "rig"').where('thirtieth_rig_dates @> date ?', "#{search_term}")
    sequence31 = Sequence.select('id, company, signature, thirty_first_rig_shop_num AS "shop_num", thirty_first AS "rig"').where('thirty_first_rig_dates @> date ?', "#{search_term}")
    sequence32 = Sequence.select('id, company, signature, thirty_second_rig_shop_num AS "shop_num", thirty_second AS "rig"').where('thirty_second_rig_dates @> date ?', "#{search_term}")
    sequence33 = Sequence.select('id, company, signature, thirty_third_rig_shop_num AS "shop_num", thirty_third AS "rig"').where('thirty_third_rig_dates @> date ?', "#{search_term}")
    sequence34 = Sequence.select('id, company, signature, thirty_fourth_rig_shop_num AS "shop_num", thirty_fourth AS "rig"').where('thirty_fourth_rig_dates @> date ?', "#{search_term}")
    sequence35 = Sequence.select('id, company, signature, thirty_fifth_rig_shop_num AS "shop_num", thirty_fifth AS "rig"').where('thirty_fifth_rig_dates @> date ?', "#{search_term}")
    sequence36 = Sequence.select('id, company, signature, thirty_sixth_rig_shop_num AS "shop_num", thirty_sixth AS "rig"').where('thirty_sixth_rig_dates @> date ?', "#{search_term}")
    sequence37 = Sequence.select('id, company, signature, thirty_seventh_rig_shop_num AS "shop_num", thirty_seventh AS "rig"').where('thirty_seventh_rig_dates @> date ?', "#{search_term}")
    sequence38 = Sequence.select('id, company, signature, thirty_eighth_rig_shop_num AS "shop_num", thirty_eighth AS "rig"').where('thirty_eighth_rig_dates @> date ?', "#{search_term}")
    sequence39 = Sequence.select('id, company, signature, thirty_ninth_rig_shop_num AS "shop_num", thirty_ninth AS "rig"').where('thirty_ninth_rig_dates @> date ?', "#{search_term}")
    sequence40 = Sequence.select('id, company, signature, fortieth_rig_shop_num AS "shop_num", fortieth AS "rig"').where('fortieth_rig_dates @> date ?', "#{search_term}")
    sequence41 = Sequence.select('id, company, signature, forty_first_rig_shop_num AS "shop_num", forty_first AS "rig"').where('forty_first_rig_dates @> date ?', "#{search_term}")
    sequence42 = Sequence.select('id, company, signature, forty_second_rig_shop_num AS "shop_num", forty_second AS "rig"').where('forty_second_rig_dates @> date ?', "#{search_term}")
    sequence43 = Sequence.select('id, company, signature, forty_third_rig_shop_num AS "shop_num", forty_third AS "rig"').where('forty_third_rig_dates @> date ?', "#{search_term}")
    sequence44 = Sequence.select('id, company, signature, forty_fourth_rig_shop_num AS "shop_num", forty_fourth AS "rig"').where('forty_fourth_rig_dates @> date ?', "#{search_term}")
    sequence45 = Sequence.select('id, company, signature, forty_fifth_rig_shop_num AS "shop_num", forty_fifth AS "rig"').where('forty_fifth_rig_dates @> date ?', "#{search_term}")
    sequence46 = Sequence.select('id, company, signature, forty_sixth_rig_shop_num AS "shop_num", forty_sixth AS "rig"').where('forty_sixth_rig_dates @> date ?', "#{search_term}")
    sequence47 = Sequence.select('id, company, signature, forty_seventh_rig_shop_num AS "shop_num", forty_seventh AS "rig"').where('forty_seventh_rig_dates @> date ?', "#{search_term}")
    sequence48 = Sequence.select('id, company, signature, forty_eighth_rig_shop_num AS "shop_num", forty_eighth AS "rig"').where('forty_eighth_rig_dates @> date ?', "#{search_term}")
    sequence49 = Sequence.select('id, company, signature, forty_ninth_rig_shop_num AS "shop_num", forty_ninth AS "rig"').where('forty_ninth_rig_dates @> date ?', "#{search_term}")
    sequence50 = Sequence.select('id, company, signature, fiftieth_rig_shop_num AS "shop_num", fiftieth AS "rig"').where('fiftieth_rig_dates @> date ?', "#{search_term}")
    sequence51 = Sequence.select('id, company, signature, fifty_first_rig_shop_num AS "shop_num", fifty_first AS "rig"').where('fifty_first_rig_dates @> date ?', "#{search_term}")
    sequence52 = Sequence.select('id, company, signature, fifty_second_rig_shop_num AS "shop_num", fifty_second AS "rig"').where('fifty_second_rig_dates @> date ?', "#{search_term}")
    sequence53 = Sequence.select('id, company, signature, fifty_third_rig_shop_num AS "shop_num", fifty_third AS "rig"').where('fifty_third_rig_dates @> date ?', "#{search_term}")
    sequence54 = Sequence.select('id, company, signature, fifty_fourth_rig_shop_num AS "shop_num", fifty_fourth AS "rig"').where('fifty_fourth_rig_dates @> date ?', "#{search_term}")
    sequence55 = Sequence.select('id, company, signature, fifty_fifth_rig_shop_num AS "shop_num", fifty_fifth AS "rig"').where('fifty_fifth_rig_dates @> date ?', "#{search_term}")
    sequence56 = Sequence.select('id, company, signature, fifty_sixth_rig_shop_num AS "shop_num", fifty_sixth AS "rig"').where('fifty_sixth_rig_dates @> date ?', "#{search_term}")
    sequence57 = Sequence.select('id, company, signature, fifty_seventh_rig_shop_num AS "shop_num", fifty_seventh AS "rig"').where('fifty_seventh_rig_dates @> date ?', "#{search_term}")
    sequence58 = Sequence.select('id, company, signature, fifty_eighth_rig_shop_num AS "shop_num", fifty_eighth AS "rig"').where('fifty_eighth_rig_dates @> date ?', "#{search_term}")
    sequence59 = Sequence.select('id, company, signature, fifty_ninth_rig_shop_num AS "shop_num", fifty_ninth AS "rig"').where('fifty_ninth_rig_dates @> date ?', "#{search_term}")
    sequence60 = Sequence.select('id, company, signature, sixtieth_rig_shop_num AS "shop_num", sixtieth AS "rig"').where('sixtieth_rig_dates @> date ?', "#{search_term}")
    sequence61 = Sequence.select('id, company, signature, sixty_first_rig_shop_num AS "shop_num", sixty_first AS "rig"').where('sixty_first_rig_dates @> date ?', "#{search_term}")
    sequence62 = Sequence.select('id, company, signature, sixty_second_rig_shop_num AS "shop_num", sixty_second AS "rig"').where('sixty_second_rig_dates @> date ?', "#{search_term}")
    sequence63 = Sequence.select('id, company, signature, sixty_third_rig_shop_num AS "shop_num", sixty_third AS "rig"').where('sixty_third_rig_dates @> date ?', "#{search_term}")
    sequence64 = Sequence.select('id, company, signature, sixty_fourth_rig_shop_num AS "shop_num", sixty_fourth AS "rig"').where('sixty_fourth_rig_dates @> date ?', "#{search_term}")
    sequence65 = Sequence.select('id, company, signature, sixty_fifth_rig_shop_num AS "shop_num", sixty_fifth AS "rig"').where('sixty_fifth_rig_dates @> date ?', "#{search_term}")
    sequence66 = Sequence.select('id, company, signature, sixty_sixth_rig_shop_num AS "shop_num", sixty_sixth AS "rig"').where('sixty_sixth_rig_dates @> date ?', "#{search_term}")
    sequence67 = Sequence.select('id, company, signature, sixty_seventh_rig_shop_num AS "shop_num", sixty_seventh AS "rig"').where('sixty_seventh_rig_dates @> date ?', "#{search_term}")
    sequence68 = Sequence.select('id, company, signature, sixty_eighth_rig_shop_num AS "shop_num", sixty_eighth AS "rig"').where('sixty_eighth_rig_dates @> date ?', "#{search_term}")
    sequence69 = Sequence.select('id, company, signature, sixty_ninth_rig_shop_num AS "shop_num", sixty_ninth AS "rig"').where('sixty_ninth_rig_dates @> date ?', "#{search_term}")
    sequence70 = Sequence.select('id, company, signature, seventieth_rig_shop_num AS "shop_num", seventieth AS "rig"').where('seventieth_rig_dates @> date ?', "#{search_term}")
    sequence71 = Sequence.select('id, company, signature, seventy_first_rig_shop_num AS "shop_num", seventy_first AS "rig"').where('seventy_first_rig_dates @> date ?', "#{search_term}")
    sequence72 = Sequence.select('id, company, signature, seventy_second_rig_shop_num AS "shop_num", seventy_second AS "rig"').where('seventy_second_rig_dates @> date ?', "#{search_term}")
    sequence73 = Sequence.select('id, company, signature, seventy_third_rig_shop_num AS "shop_num", seventy_third AS "rig"').where('seventy_third_rig_dates @> date ?', "#{search_term}")
    sequence74 = Sequence.select('id, company, signature, seventy_fourth_rig_shop_num AS "shop_num", seventy_fourth AS "rig"').where('seventy_fourth_rig_dates @> date ?', "#{search_term}")
    sequence75 = Sequence.select('id, company, signature, seventy_fifth_rig_shop_num AS "shop_num", seventy_fifth AS "rig"').where('seventy_fifth_rig_dates @> date ?', "#{search_term}")
    sequence76 = Sequence.select('id, company, signature, seventy_fifth_rig_shop_num AS "shop_num", seventy_fifth AS "rig"').where('seventy_fifth_rig_dates @> date ?', "#{search_term}")
    sequence77 = Sequence.select('id, company, signature, seventy_seventh_rig_shop_num AS "shop_num", seventy_seventh AS "rig"').where('seventy_seventh_rig_dates @> date ?', "#{search_term}")
    sequence78 = Sequence.select('id, company, signature, seventy_eighth_rig_shop_num AS "shop_num", seventy_eighth AS "rig"').where('seventy_eighth_rig_dates @> date ?', "#{search_term}")
    sequence79 = Sequence.select('id, company, signature, seventy_ninth_rig_shop_num AS "shop_num", seventy_ninth AS "rig"').where('seventy_ninth_rig_dates @> date ?', "#{search_term}")
    sequence80 = Sequence.select('id, company, signature, eightieth_rig_shop_num AS "shop_num", eightieth AS "rig"').where('eightieth_rig_dates @> date ?', "#{search_term}")
    sequence81 = Sequence.select('id, company, signature, eighty_first_rig_shop_num AS "shop_num", eighty_first AS "rig"').where('eighty_first_rig_dates @> date ?', "#{search_term}")
    sequence82 = Sequence.select('id, company, signature, eighty_second_rig_shop_num AS "shop_num", eighty_second AS "rig"').where('eighty_second_rig_dates @> date ?', "#{search_term}")
    sequence83 = Sequence.select('id, company, signature, eighty_third_rig_shop_num AS "shop_num", eighty_third AS "rig"').where('eighty_third_rig_dates @> date ?', "#{search_term}")
    sequence84 = Sequence.select('id, company, signature, eighty_fourth_rig_shop_num AS "shop_num", eighty_fourth AS "rig"').where('eighty_fourth_rig_dates @> date ?', "#{search_term}")
    sequence85 = Sequence.select('id, company, signature, eighty_fifth_rig_shop_num AS "shop_num", eighty_fifth AS "rig"').where('eighty_fifth_rig_dates @> date ?', "#{search_term}")
    sequence86 = Sequence.select('id, company, signature, eighty_sixth_rig_shop_num AS "shop_num", eighty_sixth AS "rig"').where('eighty_sixth_rig_dates @> date ?', "#{search_term}")
    sequence87 = Sequence.select('id, company, signature, eighty_seventh_rig_shop_num AS "shop_num", eighty_seventh AS "rig"').where('eighty_seventh_rig_dates @> date ?', "#{search_term}")
    sequence88 = Sequence.select('id, company, signature, eighty_eighth_rig_shop_num AS "shop_num", eighty_eighth AS "rig"').where('eighty_eighth_rig_dates @> date ?', "#{search_term}")
    sequence89 = Sequence.select('id, company, signature, eighty_ninth_rig_shop_num AS "shop_num", eighty_ninth AS "rig"').where('eighty_ninth_rig_dates @> date ?', "#{search_term}")
    sequence90 = Sequence.select('id, company, signature, nintieth_rig_shop_num AS "shop_num", nintieth AS "rig"').where('nintieth_rig_dates @> date ?', "#{search_term}")
    sequence91 = Sequence.select('id, company, signature, ninety_first_rig_shop_num AS "shop_num", ninety_first AS "rig"').where('ninety_first_rig_dates @> date ?', "#{search_term}")
    sequence92 = Sequence.select('id, company, signature, ninety_second_rig_shop_num AS "shop_num", ninety_second AS "rig"').where('ninety_second_rig_dates @> date ?', "#{search_term}")
    sequence93 = Sequence.select('id, company, signature, ninety_first_rig_shop_num AS "shop_num", ninety_first AS "rig"').where('ninety_first_rig_dates @> date ?', "#{search_term}")
    sequence94 = Sequence.select('id, company, signature, ninety_fourth_rig_shop_num AS "shop_num", ninety_fourth AS "rig"').where('ninety_fourth_rig_dates @> date ?', "#{search_term}")
    sequence95 = Sequence.select('id, company, signature, ninety_fifth_rig_shop_num AS "shop_num", ninety_fifth AS "rig"').where('ninety_fifth_rig_dates @> date ?', "#{search_term}")
    sequence96 = Sequence.select('id, company, signature, ninety_sixth_rig_shop_num AS "shop_num", ninety_sixth AS "rig"').where('ninety_sixth_rig_dates @> date ?', "#{search_term}")
    sequence97 = Sequence.select('id, company, signature, ninety_seventh_rig_shop_num AS "shop_num", ninety_seventh AS "rig"').where('ninety_seventh_rig_dates @> date ?', "#{search_term}")
    sequence98 = Sequence.select('id, company, signature, ninety_eighth_rig_shop_num AS "shop_num", ninety_eighth AS "rig"').where('ninety_eighth_rig_dates @> date ?', "#{search_term}")
    sequence99 = Sequence.select('id, company, signature, ninety_ninth_rig_shop_num AS "shop_num", ninety_ninth AS "rig"').where('ninety_ninth_rig_dates @> date ?', "#{search_term}")
    sequence100 = Sequence.select('id, company, signature, hundredth_rig_shop_num AS "shop_num", hundredth AS "rig"').where('hundredth_rig_dates @> date ?', "#{search_term}")
    sequence101 = Sequence.select('id, company, signature, hundred_and_first_rig_shop_num AS "shop_num", hundred_and_first AS "rig"').where('hundred_and_first_rig_dates @> date ?', "#{search_term}")
    sequence102 = Sequence.select('id, company, signature, hundred_and_second_rig_shop_num AS "shop_num", hundred_and_second AS "rig"').where('hundred_and_second_rig_dates @> date ?', "#{search_term}")
    sequence103 = Sequence.select('id, company, signature, hundred_and_third_rig_shop_num AS "shop_num", hundred_and_third AS "rig"').where('hundred_and_third_rig_dates @> date ?', "#{search_term}")
    sequence104 = Sequence.select('id, company, signature, hundred_and_fourth_rig_shop_num AS "shop_num", hundred_and_fourth AS "rig"').where('hundred_and_fourth_rig_dates @> date ?', "#{search_term}")
    sequence105 = Sequence.select('id, company, signature, hundred_and_fifth_rig_shop_num AS "shop_num", hundred_and_fifth AS "rig"').where('hundred_and_fifth_rig_dates @> date ?', "#{search_term}")
    sequence106 = Sequence.select('id, company, signature, hundred_and_sixth_rig_shop_num AS "shop_num", hundred_and_sixth AS "rig"').where('hundred_and_sixth_rig_dates @> date ?', "#{search_term}")
    sequence107 = Sequence.select('id, company, signature, hundred_and_seventh_rig_shop_num AS "shop_num", hundred_and_seventh AS "rig"').where('hundred_and_seventh_rig_dates @> date ?', "#{search_term}")
    sequence108 = Sequence.select('id, company, signature, hundred_and_eighth_rig_shop_num AS "shop_num", hundred_and_eighth AS "rig"').where('hundred_and_eighth_rig_dates @> date ?', "#{search_term}")
    sequence109 = Sequence.select('id, company, signature, hundred_and_ninth_rig_shop_num AS "shop_num", hundred_and_ninth AS "rig"').where('hundred_and_ninth_rig_dates @> date ?', "#{search_term}")
    sequence110 = Sequence.select('id, company, signature, hundred_and_tenth_rig_shop_num AS "shop_num", hundred_and_tenth AS "rig"').where('hundred_and_tenth_rig_dates @> date ?', "#{search_term}")
    sequence111 = Sequence.select('id, company, signature, hundred_and_eleventh_rig_shop_num AS "shop_num", hundred_and_eleventh AS "rig"').where('hundred_and_eleventh_rig_dates @> date ?', "#{search_term}")
    sequence112 = Sequence.select('id, company, signature, hundred_and_twelfth_rig_shop_num AS "shop_num", hundred_and_twelfth AS "rig"').where('hundred_and_twelfth_rig_dates @> date ?', "#{search_term}")
    sequence113 = Sequence.select('id, company, signature, hundred_and_thirteenth_rig_shop_num AS "shop_num", hundred_and_thirteenth AS "rig"').where('hundred_and_thirteenth_rig_dates @> date ?', "#{search_term}")
    sequence114 = Sequence.select('id, company, signature, hundred_and_fourteenth_rig_shop_num AS "shop_num", hundred_and_fourteenth AS "rig"').where('hundred_and_fourteenth_rig_dates @> date ?', "#{search_term}")
    sequence115 = Sequence.select('id, company, signature, hundred_and_fifteenth_rig_shop_num AS "shop_num", hundred_and_fifteenth AS "rig"').where('hundred_and_fifteenth_rig_dates @> date ?', "#{search_term}")
    sequence116 = Sequence.select('id, company, signature, hundred_and_sixteenth_rig_shop_num AS "shop_num", hundred_and_sixteenth AS "rig"').where('hundred_and_sixteenth_rig_dates @> date ?', "#{search_term}")
    sequence117 = Sequence.select('id, company, signature, hundred_and_seventeenth_rig_shop_num AS "shop_num", hundred_and_seventeenth AS "rig"').where('hundred_and_seventeenth_rig_dates @> date ?', "#{search_term}")
    sequence118 = Sequence.select('id, company, signature, hundred_and_eighteenth_rig_shop_num AS "shop_num", hundred_and_eighteenth AS "rig"').where('hundred_and_eighteenth_rig_dates @> date ?', "#{search_term}")
    sequence119 = Sequence.select('id, company, signature, hundred_and_nineteenth_rig_shop_num AS "shop_num", hundred_and_nineteenth AS "rig"').where('hundred_and_nineteenth_rig_dates @> date ?', "#{search_term}")
    sequence120 = Sequence.select('id, company, signature, hundred_and_twentieth_rig_shop_num AS "shop_num", hundred_and_twentieth AS "rig"').where('hundred_and_twentieth_rig_dates @> date ?', "#{search_term}")
    sequence121 = Sequence.select('id, company, signature, hundred_and_twenty_first_rig_shop_num AS "shop_num", hundred_and_twenty_first AS "rig"').where('hundred_and_twenty_first_rig_dates @> date ?', "#{search_term}")
    sequence122 = Sequence.select('id, company, signature, hundred_and_twenty_second_rig_shop_num AS "shop_num", hundred_and_twenty_second AS "rig"').where('hundred_and_twenty_second_rig_dates @> date ?', "#{search_term}")
    sequence123 = Sequence.select('id, company, signature, hundred_and_twenty_third_rig_shop_num AS "shop_num", hundred_and_twenty_third AS "rig"').where('hundred_and_twenty_third_rig_dates @> date ?', "#{search_term}")
    sequence124 = Sequence.select('id, company, signature, hundred_and_twenty_fourth_rig_shop_num AS "shop_num", hundred_and_twenty_fourth AS "rig"').where('hundred_and_twenty_fourth_rig_dates @> date ?', "#{search_term}")
    sequence125 = Sequence.select('id, company, signature, hundred_and_twenty_fifth_rig_shop_num AS "shop_num", hundred_and_twenty_fifth AS "rig"').where('hundred_and_twenty_fifth_rig_dates @> date ?', "#{search_term}")
    sequence126 = Sequence.select('id, company, signature, hundred_and_twenty_sixth_rig_shop_num AS "shop_num", hundred_and_twenty_sixth AS "rig"').where('hundred_and_twenty_sixth_rig_dates @> date ?', "#{search_term}")
    sequence127 = Sequence.select('id, company, signature, hundred_and_twenty_seventh_rig_shop_num AS "shop_num", hundred_and_twenty_seventh AS "rig"').where('hundred_and_twenty_seventh_rig_dates @> date ?', "#{search_term}")
    sequence128 = Sequence.select('id, company, signature, hundred_and_twenty_eighth_rig_shop_num AS "shop_num", hundred_and_twenty_eighth AS "rig"').where('hundred_and_twenty_eighth_rig_dates @> date ?', "#{search_term}")
    sequence129 = Sequence.select('id, company, signature, hundred_and_twenty_ninth_rig_shop_num AS "shop_num", hundred_and_twenty_ninth AS "rig"').where('hundred_and_twenty_ninth_rig_dates @> date ?', "#{search_term}")
    sequence130 = Sequence.select('id, company, signature, hundred_and_thirtieth_rig_shop_num AS "shop_num", hundred_and_thirtieth AS "rig"').where('hundred_and_thirtieth_rig_dates @> date ?', "#{search_term}")

    all_results = sequence1 + sequence2 + sequence3 + sequence4 + sequence5 + sequence6 + sequence7 + sequence8 + sequence9 + sequence10 + sequence11 + sequence12 + sequence13 + sequence14 + sequence15 + sequence16 + sequence17 + sequence18 + sequence19 + sequence20 + sequence21 + sequence22 + sequence23 + sequence24 + sequence25 + sequence26 + sequence27 + sequence28 + sequence29 + sequence30 + sequence31 + sequence32 + sequence33 + sequence34 +sequence35 + sequence36 + sequence37 + sequence38 + sequence39 + sequence40 + sequence41 + sequence42 + sequence43 + sequence44 + sequence45 + sequence46 + sequence47 + sequence48 + sequence49 + sequence50 + sequence51 + sequence52 + sequence53 + sequence54 + sequence55 + sequence56 + sequence57 + sequence58 + sequence59 + sequence60 + sequence61 + sequence62 + sequence63 + sequence64 + sequence65 + sequence66 + sequence67 + sequence68 + sequence69 + sequence70 + sequence71 + sequence72 + sequence73 + sequence74 + sequence75 + sequence76 + sequence77 + sequence78 + sequence79 + sequence80 + sequence81 + sequence82 + sequence83 + sequence84 + sequence85 + sequence86 + sequence87 + sequence88 + sequence89 + sequence90 + sequence91 + sequence92 + sequence93 + sequence94 + sequence95 + sequence96 + sequence97 + sequence98 + sequence99 + sequence100 + sequence101 + sequence102 + sequence103 + sequence104 + sequence105 + sequence106 + sequence107 + sequence108 + sequence109 + sequence110 + sequence111 + sequence112 + sequence113 + sequence114 + sequence115 + sequence116 + sequence117 + sequence118 + sequence119 + sequence120 + sequence121 + sequence122 + sequence123 + sequence124 + sequence125 + sequence126 + sequence127 + sequence128 + sequence129 + sequence130

    @search_results = all_results.sort_by(&:id)
    # sort_by(&:signature)
    # sort_by { |s| s[:signature] }
    # sort {|a, b| a[:signature] <=> b[:signature]}
    # above don't work 100% due to signature being varchar with dashes; id works but will require table realignment when done with all entries

    # @search_results = Sequence.where('first_rig_dates @> date ?', "#{search_term}")
    #     .or(Sequence.where('second_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('third_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('fourth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('fifth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('sixth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('seventh_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('eighth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('ninth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('tenth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('eleventh_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twelfth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('thirteenth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('fourteenth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('fifteenth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('sixteenth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('seventeenth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('eighteenth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('nineteenth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twentieth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twenty_first_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twenty_second_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twenty_third_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twenty_fourth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twenty_fifth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twenty_sixth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twenty_seventh_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twenty_eighth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('twenty_ninth_rig_dates @> date ?', "#{search_term}"))
    #     .or(Sequence.where('thirtieth_rig_dates @> date ?', "#{search_term}"))

    render 'search_co.html.erb'
  end
end
